# qnx-cmake.bbclass -- build a CMake project with the QNX SDP toolchain.
#
# Deliberately NOT built on OE's cmake.bbclass: that class assumes Yocto's own
# cross-toolchain, its sysroot layout, and a native cmake recipe, all of which
# qnx-sdp.bbclass switches off. It is less work to drive cmake directly than to
# unpick those assumptions.
#
# CMake has first-class QNX support (CMAKE_SYSTEM_NAME QNX), so the generated
# toolchain file below is close to what a QNX project would write by hand. It is
# modelled on src/rpi-gpio/qnx/build/aarch64-qnx.cmake in the QNX hypervisor
# project, with one addition: CMAKE_FIND_ROOT_PATH also covers the recipe
# sysroot, so a project can find headers and libraries produced by another
# recipe it DEPENDS on -- not just those shipped by the SDP.

inherit qnx-sdp

# cmake/ninja come from the host, allowed through bitbake's sanitized PATH by
# the HOSTTOOLS addition in conf/layer.conf. It cannot be done here: HOSTTOOLS
# symlinks are created once at cooker startup, before any class is inherited.
OECMAKE_GENERATOR ?= "Ninja"
OECMAKE_BUILD_TYPE ?= "Release"
OECMAKE_SOURCEPATH ?= "${S}"
OECMAKE_EXTRA_ARGS ?= ""

# Where the project's own install() rules put things. Projects that follow the
# QNX convention (install to ${CMAKE_SYSTEM_PROCESSOR}/sbin and usr/include)
# land directly in the right shape for the stage tree -- see rpi-gpio.
OECMAKE_INSTALL_PREFIX ?= "${QNX_STAGE_DIR}"

B = "${WORKDIR}/build"

QNX_TOOLCHAIN_FILE = "${B}/qnx-toolchain.cmake"

do_generate_toolchain_file() {
	mkdir -p ${B}
	cat > ${QNX_TOOLCHAIN_FILE} <<EOF
# Generated by qnx-cmake.bbclass -- do not edit.
set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_VERSION 800)
set(CMAKE_SYSTEM_PROCESSOR ${QNX_PROCESSOR})

set(CMAKE_SYSROOT ${QNX_TARGET})

set(CMAKE_C_COMPILER ${QNX_HOST}/usr/bin/qcc)
set(CMAKE_CXX_COMPILER ${QNX_HOST}/usr/bin/q++)
set(CMAKE_C_COMPILER_TARGET ${QNX_VARIANT})
set(CMAKE_CXX_COMPILER_TARGET ${QNX_VARIANT})

set(CMAKE_AR ${QNX_HOST}/usr/bin/${QNX_TOOL_PREFIX}ar)
set(CMAKE_RANLIB ${QNX_HOST}/usr/bin/${QNX_TOOL_PREFIX}ranlib)
set(CMAKE_LINKER ${QNX_HOST}/usr/bin/${QNX_TOOL_PREFIX}ld)

add_definitions(-D_QNX_SOURCE)

# The recipe's CFLAGS/CXXFLAGS are folded in here rather than left to the
# environment: cmake reads those env vars only on a first configure and caches
# them, so a recipe that added a define would silently not get it on a
# reconfigure. Putting them in the toolchain file makes them part of the
# configuration itself, which is also what the project's own hand-written QNX
# toolchain file does.
set(CMAKE_C_FLAGS_INIT "-fexceptions -fPIC ${CFLAGS}")
set(CMAKE_CXX_FLAGS_INIT "-fexceptions -fPIC ${CXXFLAGS}")

# Search the SDP *and* this recipe's sysroot, so a DEPENDS on another QNX recipe
# makes its headers and libraries findable by find_path/find_library/find_package.
#
# ${RECIPE_SYSROOT} itself is listed first and does double duty. Recipes that
# inherit qnx-sdp install under ${QNX_STAGE_DIR}, but recipes that do not --
# meta-qt6's, above all -- install under the ordinary ${prefix}, so the plain
# sysroot root is what makes those reachable at all.
#
# The subtler half is that FIND_ROOT_PATH_MODE_PACKAGE is ONLY, and under ONLY
# cmake rewrites every search path to <root>/<path> *unless the path already
# lies inside one of the roots*. Qt6Config.cmake looks its components up with
#   find_package(Qt6Core PATHS ${RECIPE_SYSROOT}${libdir}/cmake NO_DEFAULT_PATH)
# -- an absolute sysroot path. With only the ${QNX_STAGE_DIR} roots that path
# was rewritten into nonsense and every component "was not found" while cmake
# cheerfully reported that the config file it wanted exists. Rooting at the
# sysroot makes such paths pass through untouched.
set(CMAKE_FIND_ROOT_PATH
    ${RECIPE_SYSROOT}
    ${QNX_TARGET}
    ${QNX_TARGET}/${QNX_PROCESSOR}
    ${RECIPE_SYSROOT}${QNX_STAGE_DIR}
    ${RECIPE_SYSROOT}${QNX_STAGE_DIR}/${QNX_PROCESSOR})
set(CMAKE_PREFIX_PATH
    ${QNX_TARGET}/${QNX_PROCESSOR}
    ${RECIPE_SYSROOT}${prefix}
    ${RECIPE_SYSROOT}${QNX_STAGE_DIR}/${QNX_PROCESSOR})

set(CMAKE_FIND_LIBRARY_PREFIXES "lib")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so;.a")

# Host tools stay host tools; everything else is looked up target-side only.
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
EOF
}
addtask generate_toolchain_file after do_patch before do_configure

# Defined directly rather than via EXPORT_FUNCTIONS: that mechanism derives sh
# function names from the class name, and a dash is illegal in one. A recipe
# that needs different behaviour overrides the task in the usual way.
do_configure() {
	# CMAKE_<LANG>_FLAGS_INIT in the toolchain file seeds the cache only on a
	# *first* configure. A build directory left over from an earlier run would
	# keep its old flags, so a recipe that adds a define appears to be ignored.
	# Removing the cache makes every configure honour the current flags.
	rm -f ${B}/CMakeCache.txt
	rm -rf ${B}/CMakeFiles

	cmake -S ${OECMAKE_SOURCEPATH} -B ${B} \
		-G "${OECMAKE_GENERATOR}" \
		-DCMAKE_TOOLCHAIN_FILE=${QNX_TOOLCHAIN_FILE} \
		-DCMAKE_BUILD_TYPE=${OECMAKE_BUILD_TYPE} \
		-DCMAKE_INSTALL_PREFIX=${OECMAKE_INSTALL_PREFIX} \
		${OECMAKE_EXTRA_ARGS}
}

do_compile() {
	cmake --build ${B} -- ${PARALLEL_MAKE}
}

do_install() {
	DESTDIR=${D} cmake --install ${B}
}
